In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import json
import requests
%matplotlib inline

In [87]:
def get_json_data(api_link):
    response = requests.get(api_link)
    if response.status_code == 200:
        data = response.json()
        return data
    else:
        print("Failed to retrieve data from the API")
        return None

In [88]:
finnifty0_api_link = 'https://watch.markethound.in/api/history/decay?name=FINNIFTY&expiry=2024-04-05T00:00:00.000Z&dte=0'
data = get_json_data(finnifty0_api_link)
finnifty0_data = data['result']
finnifty0_df = pd.DataFrame(finnifty0_data)
finnifty0_df

,_id,expiry,daysToExpiry,index,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660bf34be902589d0b5ce792,2024-04-02T00:00:00.000Z,0,FINNIFTY,1.05,2024-04-02T00:00:00.000Z,115.05,21160.75,21213.05,21123.40,21142.45,89.65,100.35,1.05,101.40,0,0
1,6602bdadbf64f91f33db0e7c,2024-03-26T00:00:00.000Z,0,FINNIFTY,5.60,2024-03-26T00:00:00.000Z,124.10,20708.55,20761.95,20689.20,20731.85,72.75,118.50,5.60,124.10,0,0
2,65f97f2a22373244b1de11f9,2024-03-19T00:00:00.000Z,0,FINNIFTY,1.35,2024-03-19T00:00:00.000Z,93.30,20588.05,20632.75,20547.90,20579.45,84.85,91.95,1.10,93.30,0,0
3,65f043e5301dfda3b6463971,2024-03-12T00:00:00.000Z,0,FINNIFTY,2.30,2024-03-12T00:00:00.000Z,171.00,20899.75,21054.35,20682.35,20847.15,372.00,98.40,2.00,100.70,0,0
4,65e70d796f2fdc852f723066,2024-03-05T00:00:00.000Z,0,FINNIFTY,4.40,2024-03-05T00:00:00.000Z,117.95,20858.10,20951.55,20822.10,20842.10,129.45,112.35,3.75,116.75,0,0

In [90]:
finnifty1_api_link = 'https://watch.markethound.in/api/history/decay?name=FINNIFTY&expiry=2024-04-05T00:00:00.000Z&dte=1'
data = get_json_data(finnifty1_api_link)
finnifty1_data = data['result']
finnifty1_df = pd.DataFrame(finnifty1_data)
finnifty1_df

,_id,expiry,daysToExpiry,index,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660bf34be902589d0b5ce79c,2024-04-02T00:00:00.000Z,1,FINNIFTY,121.55,2024-04-01T00:00:00.000Z,185.85,21186.80,21229.10,21145.40,21164.10,83.70,59.50,113.45,181.05,20.15,44.35
1,6602bdadbf64f91f33db0ea3,2024-03-26T00:00:00.000Z,1,FINNIFTY,134.40,2024-03-22T00:00:00.000Z,196.10,20768.45,20838.35,20672.30,20738.10,166.05,58.15,134.20,192.55,10.30,36.60
2,65f97f2a22373244b1de1205,2024-03-19T00:00:00.000Z,1,FINNIFTY,140.75,2024-03-18T00:00:00.000Z,209.60,20642.00,20699.20,20472.90,20579.80,226.30,68.85,138.55,209.60,47.45,62.55
3,65f043e5301dfda3b6463986,2024-03-12T00:00:00.000Z,1,FINNIFTY,123.85,2024-03-11T00:00:00.000Z,184.95,20841.65,21010.10,20840.20,20973.05,169.90,58.10,123.85,181.95,23.15,-5.50
4,65e70d796f2fdc852f723079,2024-03-05T00:00:00.000Z,1,FINNIFTY,133.20,2024-03-04T00:00:00.000Z,206.95,20916.40,20952.95,20813.45,20869.45,139.50,66.40,133.20,199.60,16.45,74.30

In [91]:
finnifty2_api_link = 'https://watch.markethound.in/api/history/decay?name=FINNIFTY&expiry=2024-04-05T00:00:00.000Z&dte=2'
data = get_json_data(finnifty2_api_link)
finnifty2_data = data['result']
finnifty2_df = pd.DataFrame(finnifty2_data)
finnifty2_df

,_id,expiry,daysToExpiry,index,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660bf34be902589d0b5ce7b1,2024-04-02T00:00:00.000Z,2,FINNIFTY,185.50,2024-03-28T00:00:00.000Z,237.50,20996.25,21135.05,20872.10,20872.10,262.95,32.90,181.20,218.40,4.45,-167.85
1,6602bdadbf64f91f33db0ec5,2024-03-26T00:00:00.000Z,2,FINNIFTY,201.35,2024-03-21T00:00:00.000Z,254.95,20714.25,20818.30,20665.00,20714.55,153.30,41.80,196.70,243.15,8.80,-23.85
2,65f97f2a22373244b1de1219,2024-03-19T00:00:00.000Z,2,FINNIFTY,212.00,2024-03-15T00:00:00.000Z,281.05,20618.50,20704.50,20536.45,20658.80,168.05,50.80,207.90,262.80,2.40,38.70
3,65f043e5301dfda3b6463993,2024-03-12T00:00:00.000Z,2,FINNIFTY,195.05,2024-03-07T00:00:00.000Z,270.60,20989.30,21057.05,20955.75,21021.15,101.30,75.55,193.25,270.60,13.10,16.25
4,65e70d796f2fdc852f72308d,2024-03-05T00:00:00.000Z,2,FINNIFTY,237.50,2024-03-01T00:00:00.000Z,277.90,20821.00,20859.20,20540.15,20558.90,319.05,31.30,236.20,268.80,37.90,-48.45

In [93]:
finnifty3_api_link = 'https://watch.markethound.in/api/history/decay?name=FINNIFTY&expiry=2024-04-05T00:00:00.000Z&dte=3'
data = get_json_data(finnifty3_api_link)
finnifty3_data = data['result']
finnifty3_df = pd.DataFrame(finnifty3_data)
finnifty3_df

,_id,expiry,index,daysToExpiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660bf34be902589d0b5ce7bc,2024-04-02T00:00:00.000Z,FINNIFTY,3,227.15,2024-03-27T00:00:00.000Z,275.85,20819.70,20852.80,20742.80,20763.70,110.00,48.70,220.95,275.85,8.75,-52.40
1,6602bdadbf64f91f33db0eda,2024-03-26T00:00:00.000Z,FINNIFTY,3,269.00,2024-03-20T00:00:00.000Z,309.00,20562.85,20678.15,20373.65,20625.65,304.50,39.75,260.90,308.75,25.85,-151.70
2,65f97f2a22373244b1de1225,2024-03-19T00:00:00.000Z,FINNIFTY,3,259.10,2024-03-14T00:00:00.000Z,364.25,20731.35,20861.95,20598.15,20656.40,263.80,88.90,256.60,348.00,-3.70,72.55
3,65f043e5301dfda3b64639a6,2024-03-12T00:00:00.000Z,FINNIFTY,3,283.20,2024-03-06T00:00:00.000Z,330.45,20994.55,21052.55,20825.70,20825.70,226.85,19.60,274.55,302.80,12.60,-26.60
4,65e70d796f2fdc852f7230a4,2024-03-05T00:00:00.000Z,FINNIFTY,3,275.60,2024-02-29T00:00:00.000Z,391.00,20469.95,20489.40,20242.75,20307.30,246.65,115.40,271.55,391.00,6.80,-88.95

In [94]:
finnifty4_api_link = 'https://watch.markethound.in/api/history/decay?name=FINNIFTY&expiry=2024-04-05T00:00:00.000Z&dte=4'
data = get_json_data(finnifty4_api_link)
finnifty4_data = data['result']
finnifty4_df = pd.DataFrame(finnifty4_data)
finnifty4_df

,_id,expiry,index,daysToExpiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660bf34be902589d0b5ce7cd,2024-04-02T00:00:00.000Z,FINNIFTY,4,280.90,2024-03-26T00:00:00.000Z,338.70,20708.55,20761.95,20689.20,20731.85,72.75,32.50,278.15,313.40,5.05,-55.15
1,6602bdadbf64f91f33db0ef0,2024-03-26T00:00:00.000Z,FINNIFTY,4,327.65,2024-03-19T00:00:00.000Z,376.00,20588.05,20632.75,20547.90,20579.45,84.85,42.25,315.35,369.90,18.90,-37.60
2,65f97f2a22373244b1de124f,2024-03-19T00:00:00.000Z,FINNIFTY,4,326.70,2024-03-13T00:00:00.000Z,354.55,20734.55,20951.75,20705.45,20951.75,246.30,20.80,308.80,347.50,-21.30,78.15
3,65f043e5301dfda3b64639b6,2024-03-12T00:00:00.000Z,FINNIFTY,4,316.30,2024-03-05T00:00:00.000Z,398.80,20858.10,20951.55,20822.10,20842.10,129.45,77.00,315.85,393.30,13.50,32.40
4,65e70d796f2fdc852f7230b0,2024-03-05T00:00:00.000Z,FINNIFTY,4,403.40,2024-02-28T00:00:00.000Z,416.50,20318.40,20625.75,20317.80,20576.00,307.95,-26.50,339.80,376.90,12.40,11.10

In [98]:
nifty0_api_link = 'https://watch.markethound.in/api/history/decay?name=NIFTY&expiry=2024-04-05T00:00:00.000Z&dte=0'
data = get_json_data(nifty0_api_link)
nifty0_data = data['result']
nifty0_df = pd.DataFrame(nifty0_data)
nifty0_df

,_id,expiry,index,daysToExpiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660e966ee902589d0bc6d953,2024-04-04T00:00:00.000Z,NIFTY,0,14.70,2024-04-04T00:00:00.000Z,134.25,22541.90,22582.70,22310.95,22564.45,271.75,88.35,10.25,103.05,0,0
1,66055c5ebf64f91f33c77d7e,2024-03-28T00:00:00.000Z,NIFTY,0,23.25,2024-03-28T00:00:00.000Z,112.80,22330.30,22509.85,22176.75,22178.95,333.10,66.95,17.70,90.20,0,0
2,65fc2146bf64f91f3310a9ad,2024-03-21T00:00:00.000Z,NIFTY,0,12.50,2024-03-21T00:00:00.000Z,112.50,22017.85,22076.35,21946.90,22006.40,129.45,100.00,5.75,112.50,0,0
3,65f2e9b5301dfda3b6b521fd,2024-03-14T00:00:00.000Z,NIFTY,0,3.40,2024-03-14T00:00:00.000Z,156.80,22144.95,22201.90,21928.65,21956.00,273.25,141.20,2.70,144.60,0,0
4,65e9ac57301dfda3b6798ed8,2024-03-07T00:00:00.000Z,NIFTY,0,6.55,2024-03-07T00:00:00.000Z,118.00,22483.60,22519.60,22439.20,22498.05,80.40,111.45,4.65,118.00,0,0

In [99]:
nifty1_api_link = 'https://watch.markethound.in/api/history/decay?name=NIFTY&expiry=2024-04-05T00:00:00.000Z&dte=1'
data = get_json_data(nifty1_api_link)
nifty1_data = data['result']
nifty1_df = pd.DataFrame(nifty1_data)
nifty1_df

,_id,expiry,index,daysToExpiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660e966ee902589d0bc6d96a,2024-04-04T00:00:00.000Z,NIFTY,1,120.85,2024-04-03T00:00:00.000Z,160.05,22435.40,22518.90,22354.00,22370.15,164.90,39.20,117.50,160.05,17.80,-129.05
1,66055c5ebf64f91f33c77d97,2024-03-28T00:00:00.000Z,NIFTY,1,105.35,2024-03-27T00:00:00.000Z,177.50,22149.00,22190.65,22058.60,22070.30,132.05,72.15,105.35,177.50,15.15,-29.95
2,65fc2146bf64f91f3310a9bf,2024-03-21T00:00:00.000Z,NIFTY,1,148.40,2024-03-20T00:00:00.000Z,199.55,21851.00,21921.70,21714.30,21872.65,207.40,50.35,147.30,198.75,35.90,-155.40
3,65f2e9b5301dfda3b6b5220a,2024-03-14T00:00:00.000Z,NIFTY,1,151.35,2024-03-13T00:00:00.000Z,224.55,21984.20,22411.65,21909.55,22403.05,502.10,36.30,151.35,187.65,6.75,28.20
4,65e9ac57301dfda3b6798ee5,2024-03-07T00:00:00.000Z,NIFTY,1,125.55,2024-03-06T00:00:00.000Z,190.60,22484.55,22486.55,22227.55,22304.55,259.00,59.80,123.10,185.35,7.55,-13.50

In [100]:
nifty2_api_link = 'https://watch.markethound.in/api/history/decay?name=NIFTY&expiry=2024-04-05T00:00:00.000Z&dte=2'
data = get_json_data(nifty2_api_link)
nifty2_data = data['result']
nifty2_df = pd.DataFrame(nifty2_data)
nifty2_df

,_id,daysToExpiry,index,expiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660e966ee902589d0bc6d974,2,NIFTY,2024-04-04T00:00:00.000Z,170.20,2024-04-02T00:00:00.000Z,212.55,22462.05,22490.10,22392.55,22434.05,97.55,38.30,169.70,208.50,10.15,91.90
1,66055c5ebf64f91f33c77dad,2,NIFTY,2024-03-28T00:00:00.000Z,182.80,2024-03-26T00:00:00.000Z,230.00,22015.05,22070.20,21994.55,22046.05,75.65,47.20,182.70,230.00,5.30,-55.25
2,65fc2146bf64f91f3310a9ce,2,NIFTY,2024-03-21T00:00:00.000Z,205.90,2024-03-19T00:00:00.000Z,255.25,21813.70,21947.40,21796.45,21937.65,150.95,42.10,205.05,248.00,7.15,-58.95
3,65f2e9b5301dfda3b6b5221c,2,NIFTY,2024-03-14T00:00:00.000Z,198.55,2024-03-12T00:00:00.000Z,233.15,22335.65,22450.70,22261.40,22341.65,189.30,22.15,195.25,220.70,10.90,-67.40
4,65e9ac57301dfda3b6798ef3,2,NIFTY,2024-03-07T00:00:00.000Z,183.40,2024-03-05T00:00:00.000Z,237.55,22345.05,22412.30,22270.00,22338.65,142.30,54.15,183.40,237.55,-1.95,40.50

In [101]:
nifty3_api_link = 'https://watch.markethound.in/api/history/decay?name=NIFTY&expiry=2024-04-05T00:00:00.000Z&dte=3'
data = get_json_data(nifty3_api_link)
nifty3_data = data['result']
nifty3_df = pd.DataFrame(nifty3_data)
nifty3_df

,_id,expiry,index,daysToExpiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660e966ee902589d0bc6d97f,2024-04-04T00:00:00.000Z,NIFTY,3,212.10,2024-04-01T00:00:00.000Z,265.50,22467.40,22521.25,22433.00,22478.05,88.25,45.70,212.10,257.80,3.60,33.35
1,66055c5ebf64f91f33c77dc2,2024-03-28T00:00:00.000Z,NIFTY,3,222.40,2024-03-22T00:00:00.000Z,283.75,22080.05,22174.45,21887.20,21969.55,287.25,42.15,222.40,264.55,-7.60,34.00
2,65fc2146bf64f91f3310a9db,2024-03-21T00:00:00.000Z,NIFTY,3,236.50,2024-03-18T00:00:00.000Z,293.80,22061.20,22121.85,21941.60,21957.70,180.25,43.30,236.50,279.80,-11.50,123.55
3,65f2e9b5301dfda3b6b5222f,2024-03-14T00:00:00.000Z,NIFTY,3,230.55,2024-03-11T00:00:00.000Z,260.85,22325.40,22511.00,22311.20,22486.95,199.80,30.30,230.55,260.85,9.85,-16.25
4,65e9ac57301dfda3b6798efe,2024-03-07T00:00:00.000Z,NIFTY,3,244.20,2024-03-04T00:00:00.000Z,282.55,22397.75,22433.50,22359.60,22399.80,73.90,34.90,241.60,279.10,6.65,59.10

In [102]:
nifty4_api_link = 'https://watch.markethound.in/api/history/decay?name=NIFTY&expiry=2024-04-05T00:00:00.000Z&dte=4'
data = get_json_data(nifty4_api_link)
nifty4_data = data['result']
nifty4_df = pd.DataFrame(nifty4_data)
nifty4_df

,_id,expiry,index,daysToExpiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660e966ee902589d0bc6d993,2024-04-04T00:00:00.000Z,NIFTY,4,266.35,2024-03-28T00:00:00.000Z,287.85,22330.30,22509.85,22176.75,22178.95,333.10,2.65,253.35,269.00,8.55,-147.75
1,66055c5ebf64f91f33c77dda,2024-03-28T00:00:00.000Z,NIFTY,4,264.70,2024-03-21T00:00:00.000Z,300.80,22017.85,22076.35,21946.90,22006.40,129.45,32.80,256.05,297.50,0.15,48.30
2,65fc2146bf64f91f3310a9e9,2024-03-21T00:00:00.000Z,NIFTY,4,278.75,2024-03-15T00:00:00.000Z,332.85,21993.30,22114.30,21936.15,22071.30,178.15,25.85,276.25,304.60,-1.05,35.60
3,65f2e9b5301dfda3b6b5223d,2024-03-14T00:00:00.000Z,NIFTY,4,254.45,2024-03-07T00:00:00.000Z,314.10,22483.60,22519.60,22439.20,22498.05,80.40,59.65,247.95,314.10,-6.40,-3.35
4,65e9ac57301dfda3b6798f0a,2024-03-07T00:00:00.000Z,NIFTY,4,304.25,2024-03-01T00:00:00.000Z,340.25,22323.05,22352.20,22113.35,22119.25,238.85,19.85,304.25,324.10,25.15,-76.75

In [103]:
sensex0_api_link = 'https://watch.markethound.in/api/history/decay?name=SENSEX&expiry=2024-04-05T00:00:00.000Z&dte=0'
data = get_json_data(sensex0_api_link)
sensex0_data = data['result']
sensex0_df = pd.DataFrame(sensex0_data)
sensex0_df

,_id,expiry,index,daysToExpiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,66055f8fbf64f91f33cc6c45,2024-03-28T00:00:00.000Z,SENSEX,0,50.35,2024-03-28T00:00:00.000Z,358.80,73594.09,74173.24,73152.89,73152.89,1020.35,253.05,45.85,303.40,0,0
1,65fd75e6bf64f91f33773d46,2024-03-22T00:00:00.000Z,SENSEX,0,33.20,2024-03-22T00:00:00.000Z,460.00,72760.72,73101.82,72175.15,72466.60,926.67,373.05,22.90,406.25,0,0
2,65f4384622373244b1ab728d,2024-03-15T00:00:00.000Z,SENSEX,0,41.80,2024-03-15T00:00:00.000Z,410.70,72551.97,72983.24,72493.83,72849.48,489.41,339.75,28.30,381.55,0,0
3,65e9ac50301dfda3b67985ab,2024-03-07T00:00:00.000Z,SENSEX,0,19.80,2024-03-07T00:00:00.000Z,408.35,74090.94,74225.69,73941.51,74132.19,284.18,388.55,14.70,408.35,0,0
4,65e1c3516f2fdc852f66dad9,2024-03-01T00:00:00.000Z,SENSEX,0,45.25,2024-03-01T00:00:00.000Z,593.55,73646.06,73806.79,72868.24,72885.45,938.55,398.50,45.25,443.75,0,0

In [104]:
sensex1_api_link = 'https://watch.markethound.in/api/history/decay?name=SENSEX&expiry=2024-04-05T00:00:00.000Z&dte=1'
data = get_json_data(sensex1_api_link)
sensex1_data = data['result']
sensex1_df = pd.DataFrame(sensex1_data)
sensex1_df

,_id,daysToExpiry,expiry,index,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,66055f8fbf64f91f33cc6c5b,1,2024-03-28T00:00:00.000Z,SENSEX,382.00,2024-03-27T00:00:00.000Z,633.05,73046.25,73133.66,72613.57,72670.59,520.09,251.05,376.30,633.05,78.60,-106.64
1,65fd75e6bf64f91f33773d56,1,2024-03-22T00:00:00.000Z,SENSEX,390.80,2024-03-21T00:00:00.000Z,606.85,72667.22,72868.32,72433.75,72664.34,434.57,216.05,389.00,606.85,-15.45,200.62
2,65f4384622373244b1ab7298,1,2024-03-15T00:00:00.000Z,SENSEX,431.45,2024-03-14T00:00:00.000Z,759.20,73080.49,73359.68,72502.52,72672.08,857.16,316.65,426.10,748.10,49.90,231.01
3,65e9ac50301dfda3b67985b7,1,2024-03-07T00:00:00.000Z,SENSEX,457.90,2024-03-06T00:00:00.000Z,642.55,74123.67,74133.91,73332.86,73484.29,801.05,163.80,450.00,621.70,49.55,-8.52
4,65e1c3516f2fdc852f66dae3,1,2024-03-01T00:00:00.000Z,SENSEX,489.95,2024-02-29T00:00:00.000Z,834.15,72683.13,72723.55,72110.38,72253.89,613.17,344.20,489.30,834.15,46.20,-202.32

In [105]:
sensex2_api_link = 'https://watch.markethound.in/api/history/decay?name=SENSEX&expiry=2024-04-05T00:00:00.000Z&dte=2'
data = get_json_data(sensex2_api_link)
sensex2_data = data['result']
sensex2_df = pd.DataFrame(sensex2_data)
sensex2_df

,_id,expiry,index,daysToExpiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,66055f8fbf64f91f33cc6c6b,2024-03-28T00:00:00.000Z,SENSEX,2,659.10,2024-03-26T00:00:00.000Z,802.65,72479.66,72690.75,72405.66,72650.35,285.09,143.55,644.85,802.65,26.05,-190.93
1,65fd75e6bf64f91f33773d6a,2024-03-22T00:00:00.000Z,SENSEX,2,715.85,2024-03-20T00:00:00.000Z,830.10,72140.37,72392.74,71681.72,72198.34,711.02,90.40,685.80,806.25,109.00,-523.97
2,65f4384622373244b1ab72a5,2024-03-15T00:00:00.000Z,SENSEX,2,756.25,2024-03-13T00:00:00.000Z,929.45,72736.78,73949.44,72534.68,73931.22,1414.76,62.30,756.25,818.55,8.15,64.70
3,65e9ac50301dfda3b67985c8,2024-03-07T00:00:00.000Z,SENSEX,2,644.85,2024-03-05T00:00:00.000Z,831.35,73653.43,73909.36,73415.53,73657.31,493.83,178.45,644.85,823.30,23.15,169.14
4,65e1c3516f2fdc852f66daef,2024-03-01T00:00:00.000Z,SENSEX,2,865.75,2024-02-28T00:00:00.000Z,1004.05,72255.28,73218.27,72237.59,73154.22,980.68,55.90,832.60,921.65,31.60,1.39

In [106]:
sensex3_api_link = 'https://watch.markethound.in/api/history/decay?name=SENSEX&expiry=2024-04-05T00:00:00.000Z&dte=3'
data = get_json_data(sensex3_api_link)
sensex3_data = data['result']
sensex3_df = pd.DataFrame(sensex3_data)
sensex3_df

,_id,expiry,index,daysToExpiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,66055f8fbf64f91f33cc6c7f,2024-03-28T00:00:00.000Z,SENSEX,3,786.95,2024-03-22T00:00:00.000Z,1029.00,72760.72,73101.82,72175.15,72466.60,926.67,92.55,786.95,879.50,-15.70,110.37
1,65fd75e6bf64f91f33773d7a,2024-03-22T00:00:00.000Z,SENSEX,3,846.85,2024-03-19T00:00:00.000Z,970.70,72016.68,72412.96,71936.86,72382.20,476.10,71.80,828.95,918.65,40.60,-181.66
2,65f4384622373244b1ab72b7,2024-03-15T00:00:00.000Z,SENSEX,3,857.75,2024-03-12T00:00:00.000Z,935.70,73700.99,74000.46,73368.40,73542.63,632.06,75.50,816.50,933.25,39.20,-230.23
3,65e9ac50301dfda3b67985d4,2024-03-07T00:00:00.000Z,SENSEX,3,836.40,2024-03-04T00:00:00.000Z,1055.00,73874.03,73978.32,73753.80,73878.79,224.52,212.25,836.40,1048.65,13.10,216.72
4,65e1c3516f2fdc852f66dafd,2024-03-01T00:00:00.000Z,SENSEX,3,950.80,2024-02-27T00:00:00.000Z,1119.25,73072.63,73152.24,72671.95,72717.94,480.29,155.30,950.80,1106.10,29.15,-81.59

In [107]:
sensex4_api_link = 'https://watch.markethound.in/api/history/decay?name=SENSEX&expiry=2024-04-05T00:00:00.000Z&dte=4'
data = get_json_data(sensex4_api_link)
sensex4_data = data['result']
sensex4_df = pd.DataFrame(sensex4_data)
sensex4_df

,_id,expiry,index,daysToExpiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,66055f8fbf64f91f33cc6c8f,2024-03-28T00:00:00.000Z,SENSEX,4,957.70,2024-03-21T00:00:00.000Z,1204.80,72667.22,72868.32,72433.75,72664.34,434.57,247.10,746.15,1204.80,78.20,200.62
1,65fd75e6bf64f91f33773d88,2024-03-22T00:00:00.000Z,SENSEX,4,930.85,2024-03-18T00:00:00.000Z,1157.05,72761.26,72981.68,72409.86,72479.25,571.82,226.20,930.85,1157.05,12.20,379.06
2,65f4384622373244b1ab72c2,2024-03-15T00:00:00.000Z,SENSEX,4,931.35,2024-03-11T00:00:00.000Z,1063.75,73509.16,74119.30,73437.72,74047.72,681.58,110.50,921.80,1041.85,-1.90,-33.47
3,65e9ac50301dfda3b67985e0,2024-03-07T00:00:00.000Z,SENSEX,4,1118.95,2024-03-01T00:00:00.000Z,1289.20,73646.06,73806.79,72868.24,72885.45,938.55,96.55,890.85,1215.50,70.30,-232.73
4,65e1c3516f2fdc852f66db09,2024-03-01T00:00:00.000Z,SENSEX,4,1131.65,2024-02-26T00:00:00.000Z,1213.45,72794.18,73076.30,72674.03,72981.68,402.27,62.25,1079.20,1193.90,25.55,76.24

In [108]:
bankex0_api_link = 'https://watch.markethound.in/api/history/decay?name=BANKEX&expiry=2024-04-05T00:00:00.000Z&dte=0'
data = get_json_data(bankex0_api_link)
bankex0_data = data['result']
bankex0_df = pd.DataFrame(bankex0_data)
bankex0_df

,_id,daysToExpiry,expiry,index,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660aa1ebe902589d0b51499d,0,2024-04-01T00:00:00.000Z,BANKEX,3.90,2024-04-01T00:00:00.000Z,351.95,53901.72,54029.85,53778.56,53859.28,251.29,324.95,3.90,328.85,0,0
1,65fd7860bf64f91f3379e80a,0,2024-03-22T00:00:00.000Z,BANKEX,9.55,2024-03-22T00:00:00.000Z,437.20,53071.52,53230.82,52860.64,52993.25,370.18,356.65,9.55,366.20,0,0
2,65f82cd622373244b17ca91d,0,2024-03-18T00:00:00.000Z,BANKEX,47.65,2024-03-18T00:00:00.000Z,365.40,52924.59,53025.61,52362.46,52686.69,663.15,251.90,29.55,299.55,0,0
3,65eef243301dfda3b608f37b,0,2024-03-11T00:00:00.000Z,BANKEX,11.05,2024-03-11T00:00:00.000Z,314.45,53774.63,54322.91,53709.29,54282.88,613.62,303.40,4.85,314.45,0,0
4,65e5bcfe6f2fdc852f35afd3,0,2024-03-04T00:00:00.000Z,BANKEX,39.45,2024-03-04T00:00:00.000Z,358.10,53963.42,54032.40,53676.15,53803.52,356.25,308.85,29.35,348.30,0,0

In [109]:
bankex1_api_link = 'https://watch.markethound.in/api/history/decay?name=BANKEX&expiry=2024-04-05T00:00:00.000Z&dte=1'
data = get_json_data(bankex1_api_link)
bankex1_data = data['result']
bankex1_df = pd.DataFrame(bankex1_data)
bankex1_df

,_id,daysToExpiry,expiry,index,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660aa1ebe902589d0b5149a8,1,2024-04-01T00:00:00.000Z,BANKEX,355.15,2024-03-28T00:00:00.000Z,499.25,53483.10,53820.08,53232.34,53265.06,587.74,118.05,348.55,473.20,26.30,-376.18
1,65fd7860bf64f91f3379e819,1,2024-03-22T00:00:00.000Z,BANKEX,358.45,2024-03-21T00:00:00.000Z,579.80,52980.75,53319.11,52843.60,53072.19,475.51,221.35,341.00,579.80,-7.75,-12.50
2,65f82cd622373244b17ca929,1,2024-03-18T00:00:00.000Z,BANKEX,373.05,2024-03-15T00:00:00.000Z,612.80,52788.15,53052.13,52517.42,52936.48,534.71,204.00,373.05,577.05,73.50,101.46
3,65eef243301dfda3b608f386,1,2024-03-11T00:00:00.000Z,BANKEX,369.40,2024-03-07T00:00:00.000Z,615.85,54324.85,54654.14,54300.43,54588.15,353.71,205.65,354.75,575.05,54.95,41.97
4,65e5bcfe6f2fdc852f35afdf,1,2024-03-04T00:00:00.000Z,BANKEX,488.10,2024-03-01T00:00:00.000Z,657.55,53681.83,53795.77,52812.13,52821.02,983.64,99.55,481.05,587.65,139.80,-121.69

In [110]:
bankex2_api_link = 'https://watch.markethound.in/api/history/decay?name=BANKEX&expiry=2024-04-05T00:00:00.000Z&dte=2'
data = get_json_data(bankex2_api_link)
bankex2_data = data['result']
bankex2_df = pd.DataFrame(bankex2_data)
bankex2_df

,_id,daysToExpiry,index,expiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660aa1ebe902589d0b5149b3,2,BANKEX,2024-04-01T00:00:00.000Z,475.05,2024-03-27T00:00:00.000Z,718.05,53124.49,53211.58,52913.96,52932.47,297.62,243.00,471.35,718.05,1.85,-140.57
1,65fd7860bf64f91f3379e826,2,BANKEX,2024-03-22T00:00:00.000Z,603.55,2024-03-20T00:00:00.000Z,698.95,52670.30,52976.70,52112.80,52760.36,863.90,49.85,565.00,653.40,23.75,-401.89
2,65f82cd622373244b17ca93f,2,BANKEX,2024-03-18T00:00:00.000Z,555.10,2024-03-14T00:00:00.000Z,906.30,53128.66,53633.04,52948.83,53136.54,684.21,228.75,555.10,783.85,-21.95,192.18
3,65eef243301dfda3b608f392,2,BANKEX,2024-03-11T00:00:00.000Z,646.00,2024-03-06T00:00:00.000Z,827.55,54587.23,54796.36,53906.18,53906.18,890.18,89.85,639.55,735.85,70.95,-0.92
4,65e5bcfe6f2fdc852f35afee,2,BANKEX,2024-03-04T00:00:00.000Z,625.90,2024-02-29T00:00:00.000Z,952.50,52588.96,52650.89,51899.71,52096.93,751.18,293.35,620.70,919.25,38.25,-232.06

In [111]:
bankex3_api_link = 'https://watch.markethound.in/api/history/decay?name=BANKEX&expiry=2024-04-05T00:00:00.000Z&dte=3'
data = get_json_data(bankex3_api_link)
bankex3_data = data['result']
bankex3_df = pd.DataFrame(bankex3_data)
bankex3_df

,_id,expiry,index,daysToExpiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660aa1ebe902589d0b5149c4,2024-04-01T00:00:00.000Z,BANKEX,3,725.70,2024-03-26T00:00:00.000Z,905.25,52808.10,52997.59,52741.75,52991.69,255.84,-39.65,679.95,686.05,7.65,-124.37
1,65fd7860bf64f91f3379e841,2024-03-22T00:00:00.000Z,BANKEX,3,774.00,2024-03-19T00:00:00.000Z,837.00,52628.41,52797.38,52544.23,52740.17,253.15,55.25,717.00,829.25,120.60,-131.95
2,65f82cd622373244b17ca94a,2024-03-18T00:00:00.000Z,BANKEX,3,776.60,2024-03-13T00:00:00.000Z,859.90,53288.89,53837.97,53247.81,53837.97,590.16,83.30,507.50,859.90,-7.25,152.35
3,65eef243301dfda3b608f39d,2024-03-11T00:00:00.000Z,BANKEX,3,821.55,2024-03-05T00:00:00.000Z,939.95,54028.04,54246.48,53692.31,53692.31,554.17,25.45,788.10,847.00,85.70,121.86
4,65e5bcfe6f2fdc852f35b003,2024-03-04T00:00:00.000Z,BANKEX,3,1000.15,2024-02-28T00:00:00.000Z,1018.25,52159.44,53077.12,52159.44,52939.16,917.68,-22.50,873.80,977.65,80.90,62.51

In [112]:
bankex4_api_link = 'https://watch.markethound.in/api/history/decay?name=BANKEX&expiry=2024-04-05T00:00:00.000Z&dte=4'
data = get_json_data(bankex4_api_link)
bankex4_data = data['result']
bankex4_df = pd.DataFrame(bankex4_data)
bankex4_df

,_id,expiry,index,daysToExpiry,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660aa1ebe902589d0b5149d0,2024-04-01T00:00:00.000Z,BANKEX,4,890.05,2024-03-22T00:00:00.000Z,1065.80,53071.52,53230.82,52860.64,52993.25,370.18,131.05,874.75,1021.10,204.00,79.83
1,65fd7860bf64f91f3379e84d,2024-03-22T00:00:00.000Z,BANKEX,4,835.75,2024-03-18T00:00:00.000Z,942.90,52924.59,53025.61,52362.46,52686.69,663.15,91.00,570.15,926.75,6.50,184.42
2,65f82cd622373244b17ca956,2024-03-18T00:00:00.000Z,BANKEX,4,852.35,2024-03-12T00:00:00.000Z,968.45,53700.20,54299.44,53312.32,53773.29,987.12,41.80,843.05,894.15,-7.55,-137.77
3,65eef243301dfda3b608f3a8,2024-03-11T00:00:00.000Z,BANKEX,4,941.60,2024-03-04T00:00:00.000Z,1117.75,53963.42,54032.40,53676.15,53803.52,356.25,142.15,926.10,1083.75,94.60,271.11
4,65e5bcfe6f2fdc852f35b012,2024-03-04T00:00:00.000Z,BANKEX,4,969.50,2024-02-27T00:00:00.000Z,1157.25,52909.86,53022.83,52646.96,52789.33,375.87,125.85,945.75,1095.35,-8.15,-29.30

In [163]:
df=pd.concat([finnifty0_df,finnifty1_df,finnifty2_df,finnifty3_df,finnifty4_df,nifty0_df,nifty1_df,nifty2_df,nifty3_df,nifty4_df,sensex0_df,sensex1_df,sensex2_df,
              sensex3_df,sensex4_df,bankex0_df,bankex1_df,bankex2_df,bankex3_df,bankex4_df],ignore_index=True)

In [164]:
df

,_id,expiry,daysToExpiry,index,close,date,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap
0,660bf34be902589d0b5ce792,2024-04-02T00:00:00.000Z,0,FINNIFTY,1.05,2024-04-02T00:00:00.000Z,115.05,21160.75,21213.05,21123.40,21142.45,89.65,100.35,1.05,101.40,0,0
1,6602bdadbf64f91f33db0e7c,2024-03-26T00:00:00.000Z,0,FINNIFTY,5.60,2024-03-26T00:00:00.000Z,124.10,20708.55,20761.95,20689.20,20731.85,72.75,118.50,5.60,124.10,0,0
2,65f97f2a22373244b1de11f9,2024-03-19T00:00:00.000Z,0,FINNIFTY,1.35,2024-03-19T00:00:00.000Z,93.30,20588.05,20632.75,20547.90,20579.45,84.85,91.95,1.10,93.30,0,0
3,65f043e5301dfda3b6463971,2024-03-12T00:00:00.000Z,0,FINNIFTY,2.30,2024-03-12T00:00:00.000Z,171.00,20899.75,21054.35,20682.35,20847.15,372.00,98.40,2.00,100.70,0,0
4,65e70d796f2fdc852f723066,2024-03-05T00:00:00.000Z,0,FINNIFTY,4.40,2024-03-05T00:00:00.000Z,117.95,20858.10,20951.55,20822.10,20842.10,129.45,112.35,3.75,116.75,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,660aa1ebe902589d0b5149d0,2024-04-01T00:00:00.000Z,4,BANKEX,890.05,2024-03-22T00:00:00.000Z,1065.80,53071.52,53230.82,52860.64,52993.25,370.18,131.05,874.75,1021.10,204.00,79.83
96,65fd7860bf64f91f3379e84d,2024-03-22T00:00:00.000Z,4,BANKEX,835.75,2024-03-18T00:00:00.000Z,942.90,52924.59,53025.61,52362.46,52686.69,663.15,91.00,570.15,926.75,6.50,184.42
97,65f82cd622373244b17ca956,2024-03-18T00:00:00.000Z,4,BANKEX,852.35,2024-03-12T00:00:00.000Z,968.45,53700.20,54299.44,53312.32,53773.29,987.12,41.80,843.05,894.15,-7.55,-137.77
98,65eef243301dfda3b608f3a8,2024-03-11T00:00:00.000Z,4,BANKEX,941.60,2024-03-04T00:00:00.000Z,1117.75,53963.42,54032.40,53676.15,53803.52,356.25,142.15,926.10,1083.75,94.60,271.11
99,65e5bcfe6f2fdc852f35b012,2024-03-04T00:00:00.000Z,4,BANKEX,969.50,2024-02-27T00:00:00.000Z,1157.25,52909.86,53022.83,52646.96,52789.33,375.87,125.85,945.75,1095.35,-8.15,-29.30

In [165]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   _id                100 non-null    object
 1   expiry             100 non-null    object
 2   daysToExpiry       100 non-null    int64
 3   index              100 non-null    object
 4   close              100 non-null    object
 5   date               100 non-null    object
 6   high               100 non-null    object
 7   index_close        100 non-null    object
 8   index_high         100 non-null    object
 9   index_low          100 non-null    object
 10  index_open         100 non-null    object
 11  intradayMovement   100 non-null    object
 12  intradayTotal      100 non-null    object
 13  low                100 non-null    object
 14  open               100 non-null    object
 15  overnightExpected  100 non-null    object
 16  overnightGap       100 non-null    object
dtypes: int64(1), object(16)
memory usage: 13.4+ KB

In [167]:
df['expiry_column'] = pd.to_datetime(df['expiry'])
df['expiry_year'] = df['expiry_column'].dt.year
df['expiry_month'] = df['expiry_column'].dt.month
df['expiry_day'] = df['expiry_column'].dt.day
df

,_id,expiry,daysToExpiry,index,close,date,high,index_close,index_high,index_low,...,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap,expiry_column,expiry_year,expiry_month,expiry_day
0,660bf34be902589d0b5ce792,2024-04-02T00:00:00.000Z,0,FINNIFTY,1.05,2024-04-02T00:00:00.000Z,115.05,21160.75,21213.05,21123.40,...,89.65,100.35,1.05,101.40,0,0,2024-04-02 00:00:00+00:00,2024,4,2
1,6602bdadbf64f91f33db0e7c,2024-03-26T00:00:00.000Z,0,FINNIFTY,5.60,2024-03-26T00:00:00.000Z,124.10,20708.55,20761.95,20689.20,...,72.75,118.50,5.60,124.10,0,0,2024-03-26 00:00:00+00:00,2024,3,26
2,65f97f2a22373244b1de11f9,2024-03-19T00:00:00.000Z,0,FINNIFTY,1.35,2024-03-19T00:00:00.000Z,93.30,20588.05,20632.75,20547.90,...,84.85,91.95,1.10,93.30,0,0,2024-03-19 00:00:00+00:00,2024,3,19
3,65f043e5301dfda3b6463971,2024-03-12T00:00:00.000Z,0,FINNIFTY,2.30,2024-03-12T00:00:00.000Z,171.00,20899.75,21054.35,20682.35,...,372.00,98.40,2.00,100.70,0,0,2024-03-12 00:00:00+00:00,2024,3,12
4,65e70d796f2fdc852f723066,2024-03-05T00:00:00.000Z,0,FINNIFTY,4.40,2024-03-05T00:00:00.000Z,117.95,20858.10,20951.55,20822.10,...,129.45,112.35,3.75,116.75,0,0,2024-03-05 00:00:00+00:00,2024,3,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,660aa1ebe902589d0b5149d0,2024-04-01T00:00:00.000Z,4,BANKEX,890.05,2024-03-22T00:00:00.000Z,1065.80,53071.52,53230.82,52860.64,...,370.18,131.05,874.75,1021.10,204.00,79.83,2024-04-01 00:00:00+00:00,2024,4,1
96,65fd7860bf64f91f3379e84d,2024-03-22T00:00:00.000Z,4,BANKEX,835.75,2024-03-18T00:00:00.000Z,942.90,52924.59,53025.61,52362.46,...,663.15,91.00,570.15,926.75,6.50,184.42,2024-03-22 00:00:00+00:00,2024,3,22
97,65f82cd622373244b17ca956,2024-03-18T00:00:00.000Z,4,BANKEX,852.35,2024-03-12T00:00:00.000Z,968.45,53700.20,54299.44,53312.32,...,987.12,41.80,843.05,894.15,-7.55,-137.77,2024-03-18 00:00:00+00:00,2024,3,18
98,65eef243301dfda3b608f3a8,2024-03-11T00:00:00.000Z,4,BANKEX,941.60,2024-03-04T00:00:00.000Z,1117.75,53963.42,54032.40,53676.15,...,356.25,142.15,926.10,1083.75,94.60,271.11,2024-03-11 00:00:00+00:00,2024,3,11
99,65e5bcfe6f2fdc852f35b012,2024-03-04T00:00:00.000Z,4,BANKEX,969.50,2024-02-27T00:00:00.000Z,1157.25,52909.86,53022.83,52646.96,...,375.87,125.85,945.75,1095.35,-8.15,-29.30,2024-03-04 00:00:00+00:00,2024,3,4

In [168]:
df['date_column'] = pd.to_datetime(df['date'])
df['date_year'] = df['date_column'].dt.year
df['date_month'] = df['date_column'].dt.month
df['date_day'] = df['date_column'].dt.day
df

,_id,expiry,daysToExpiry,index,close,date,high,index_close,index_high,index_low,...,overnightExpected,overnightGap,expiry_column,expiry_year,expiry_month,expiry_day,date_column,date_year,date_month,date_day
0,660bf34be902589d0b5ce792,2024-04-02T00:00:00.000Z,0,FINNIFTY,1.05,2024-04-02T00:00:00.000Z,115.05,21160.75,21213.05,21123.40,...,0,0,2024-04-02 00:00:00+00:00,2024,4,2,2024-04-02 00:00:00+00:00,2024,4,2
1,6602bdadbf64f91f33db0e7c,2024-03-26T00:00:00.000Z,0,FINNIFTY,5.60,2024-03-26T00:00:00.000Z,124.10,20708.55,20761.95,20689.20,...,0,0,2024-03-26 00:00:00+00:00,2024,3,26,2024-03-26 00:00:00+00:00,2024,3,26
2,65f97f2a22373244b1de11f9,2024-03-19T00:00:00.000Z,0,FINNIFTY,1.35,2024-03-19T00:00:00.000Z,93.30,20588.05,20632.75,20547.90,...,0,0,2024-03-19 00:00:00+00:00,2024,3,19,2024-03-19 00:00:00+00:00,2024,3,19
3,65f043e5301dfda3b6463971,2024-03-12T00:00:00.000Z,0,FINNIFTY,2.30,2024-03-12T00:00:00.000Z,171.00,20899.75,21054.35,20682.35,...,0,0,2024-03-12 00:00:00+00:00,2024,3,12,2024-03-12 00:00:00+00:00,2024,3,12
4,65e70d796f2fdc852f723066,2024-03-05T00:00:00.000Z,0,FINNIFTY,4.40,2024-03-05T00:00:00.000Z,117.95,20858.10,20951.55,20822.10,...,0,0,2024-03-05 00:00:00+00:00,2024,3,5,2024-03-05 00:00:00+00:00,2024,3,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,660aa1ebe902589d0b5149d0,2024-04-01T00:00:00.000Z,4,BANKEX,890.05,2024-03-22T00:00:00.000Z,1065.80,53071.52,53230.82,52860.64,...,204.00,79.83,2024-04-01 00:00:00+00:00,2024,4,1,2024-03-22 00:00:00+00:00,2024,3,22
96,65fd7860bf64f91f3379e84d,2024-03-22T00:00:00.000Z,4,BANKEX,835.75,2024-03-18T00:00:00.000Z,942.90,52924.59,53025.61,52362.46,...,6.50,184.42,2024-03-22 00:00:00+00:00,2024,3,22,2024-03-18 00:00:00+00:00,2024,3,18
97,65f82cd622373244b17ca956,2024-03-18T00:00:00.000Z,4,BANKEX,852.35,2024-03-12T00:00:00.000Z,968.45,53700.20,54299.44,53312.32,...,-7.55,-137.77,2024-03-18 00:00:00+00:00,2024,3,18,2024-03-12 00:00:00+00:00,2024,3,12
98,65eef243301dfda3b608f3a8,2024-03-11T00:00:00.000Z,4,BANKEX,941.60,2024-03-04T00:00:00.000Z,1117.75,53963.42,54032.40,53676.15,...,94.60,271.11,2024-03-11 00:00:00+00:00,2024,3,11,2024-03-04 00:00:00+00:00,2024,3,4
99,65e5bcfe6f2fdc852f35b012,2024-03-04T00:00:00.000Z,4,BANKEX,969.50,2024-02-27T00:00:00.000Z,1157.25,52909.86,53022.83,52646.96,...,-8.15,-29.30,2024-03-04 00:00:00+00:00,2024,3,4,2024-02-27 00:00:00+00:00,2024,2,27

In [169]:
df.drop(['expiry','date','expiry_column','date_column'],axis=1,inplace=True)

In [170]:
df

,_id,daysToExpiry,index,close,high,index_close,index_high,index_low,index_open,intradayMovement,...,low,open,overnightExpected,overnightGap,expiry_year,expiry_month,expiry_day,date_year,date_month,date_day
0,660bf34be902589d0b5ce792,0,FINNIFTY,1.05,115.05,21160.75,21213.05,21123.40,21142.45,89.65,...,1.05,101.40,0,0,2024,4,2,2024,4,2
1,6602bdadbf64f91f33db0e7c,0,FINNIFTY,5.60,124.10,20708.55,20761.95,20689.20,20731.85,72.75,...,5.60,124.10,0,0,2024,3,26,2024,3,26
2,65f97f2a22373244b1de11f9,0,FINNIFTY,1.35,93.30,20588.05,20632.75,20547.90,20579.45,84.85,...,1.10,93.30,0,0,2024,3,19,2024,3,19
3,65f043e5301dfda3b6463971,0,FINNIFTY,2.30,171.00,20899.75,21054.35,20682.35,20847.15,372.00,...,2.00,100.70,0,0,2024,3,12,2024,3,12
4,65e70d796f2fdc852f723066,0,FINNIFTY,4.40,117.95,20858.10,20951.55,20822.10,20842.10,129.45,...,3.75,116.75,0,0,2024,3,5,2024,3,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,660aa1ebe902589d0b5149d0,4,BANKEX,890.05,1065.80,53071.52,53230.82,52860.64,52993.25,370.18,...,874.75,1021.10,204.00,79.83,2024,4,1,2024,3,22
96,65fd7860bf64f91f3379e84d,4,BANKEX,835.75,942.90,52924.59,53025.61,52362.46,52686.69,663.15,...,570.15,926.75,6.50,184.42,2024,3,22,2024,3,18
97,65f82cd622373244b17ca956,4,BANKEX,852.35,968.45,53700.20,54299.44,53312.32,53773.29,987.12,...,843.05,894.15,-7.55,-137.77,2024,3,18,2024,3,12
98,65eef243301dfda3b608f3a8,4,BANKEX,941.60,1117.75,53963.42,54032.40,53676.15,53803.52,356.25,...,926.10,1083.75,94.60,271.11,2024,3,11,2024,3,4
99,65e5bcfe6f2fdc852f35b012,4,BANKEX,969.50,1157.25,52909.86,53022.83,52646.96,52789.33,375.87,...,945.75,1095.35,-8.15,-29.30,2024,3,4,2024,2,27

In [171]:
df.drop(['_id'],axis=1,inplace=True)
df

,daysToExpiry,index,close,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap,expiry_year,expiry_month,expiry_day,date_year,date_month,date_day
0,0,FINNIFTY,1.05,115.05,21160.75,21213.05,21123.40,21142.45,89.65,100.35,1.05,101.40,0,0,2024,4,2,2024,4,2
1,0,FINNIFTY,5.60,124.10,20708.55,20761.95,20689.20,20731.85,72.75,118.50,5.60,124.10,0,0,2024,3,26,2024,3,26
2,0,FINNIFTY,1.35,93.30,20588.05,20632.75,20547.90,20579.45,84.85,91.95,1.10,93.30,0,0,2024,3,19,2024,3,19
3,0,FINNIFTY,2.30,171.00,20899.75,21054.35,20682.35,20847.15,372.00,98.40,2.00,100.70,0,0,2024,3,12,2024,3,12
4,0,FINNIFTY,4.40,117.95,20858.10,20951.55,20822.10,20842.10,129.45,112.35,3.75,116.75,0,0,2024,3,5,2024,3,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,4,BANKEX,890.05,1065.80,53071.52,53230.82,52860.64,52993.25,370.18,131.05,874.75,1021.10,204.00,79.83,2024,4,1,2024,3,22
96,4,BANKEX,835.75,942.90,52924.59,53025.61,52362.46,52686.69,663.15,91.00,570.15,926.75,6.50,184.42,2024,3,22,2024,3,18
97,4,BANKEX,852.35,968.45,53700.20,54299.44,53312.32,53773.29,987.12,41.80,843.05,894.15,-7.55,-137.77,2024,3,18,2024,3,12
98,4,BANKEX,941.60,1117.75,53963.42,54032.40,53676.15,53803.52,356.25,142.15,926.10,1083.75,94.60,271.11,2024,3,11,2024,3,4
99,4,BANKEX,969.50,1157.25,52909.86,53022.83,52646.96,52789.33,375.87,125.85,945.75,1095.35,-8.15,-29.30,2024,3,4,2024,2,27

In [172]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   daysToExpiry       100 non-null    int64
 1   index              100 non-null    object
 2   close              100 non-null    object
 3   high               100 non-null    object
 4   index_close        100 non-null    object
 5   index_high         100 non-null    object
 6   index_low          100 non-null    object
 7   index_open         100 non-null    object
 8   intradayMovement   100 non-null    object
 9   intradayTotal      100 non-null    object
 10  low                100 non-null    object
 11  open               100 non-null    object
 12  overnightExpected  100 non-null    object
 13  overnightGap       100 non-null    object
 14  expiry_year        100 non-null    int32
 15  expiry_month       100 non-null    int32
 16  expiry_day         100 non-null    int32
 17  date_year          100 non-null    int32
 18  date_month         100 non-null    int32
 19  date_day           100 non-null    int32
dtypes: int32(6), int64(1), object(13)
memory usage: 13.4+ KB

In [173]:
df['close']=df['close'].astype(float)
df['high']=df['high'].astype(float)
df['index_close']=df['index_close'].astype(float)
df['index_high']=df['index_high'].astype(float)
df['index_low']=df['index_low'].astype(float)
df['index_open']=df['index_open'].astype(float)
df['intradayMovement']=df['intradayMovement'].astype(float)
df['intradayTotal']=df['intradayTotal'].astype(float)
df['low']=df['low'].astype(float)
df['open']=df['open'].astype(float)
df['overnightExpected']=df['overnightExpected'].astype(float)
df['overnightGap']=df['overnightGap'].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   daysToExpiry       100 non-null    int64
 1   index              100 non-null    object
 2   close              100 non-null    float64
 3   high               100 non-null    float64
 4   index_close        100 non-null    float64
 5   index_high         100 non-null    float64
 6   index_low          100 non-null    float64
 7   index_open         100 non-null    float64
 8   intradayMovement   100 non-null    float64
 9   intradayTotal      100 non-null    float64
 10  low                100 non-null    float64
 11  open               100 non-null    float64
 12  overnightExpected  100 non-null    float64
 13  overnightGap       100 non-null    float64
 14  expiry_year        100 non-null    int32
 15  expiry_month       100 non-null    int32
 16  expiry_day         100 non-null    int32
 17  date_year          100 non-null    int32
 18  date_month         100 non-null    int32
 19  date_day           100 non-null    int32
dtypes: float64(12), int32(6), int64(1), object(1)
memory usage: 13.4+ KB

In [174]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['index_encoded'] = label_encoder.fit_transform(df['index'])
df

,daysToExpiry,index,close,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,...,open,overnightExpected,overnightGap,expiry_year,expiry_month,expiry_day,date_year,date_month,date_day,index_encoded
0,0,FINNIFTY,1.05,115.05,21160.75,21213.05,21123.40,21142.45,89.65,100.35,...,101.40,0.00,0.00,2024,4,2,2024,4,2,1
1,0,FINNIFTY,5.60,124.10,20708.55,20761.95,20689.20,20731.85,72.75,118.50,...,124.10,0.00,0.00,2024,3,26,2024,3,26,1
2,0,FINNIFTY,1.35,93.30,20588.05,20632.75,20547.90,20579.45,84.85,91.95,...,93.30,0.00,0.00,2024,3,19,2024,3,19,1
3,0,FINNIFTY,2.30,171.00,20899.75,21054.35,20682.35,20847.15,372.00,98.40,...,100.70,0.00,0.00,2024,3,12,2024,3,12,1
4,0,FINNIFTY,4.40,117.95,20858.10,20951.55,20822.10,20842.10,129.45,112.35,...,116.75,0.00,0.00,2024,3,5,2024,3,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,4,BANKEX,890.05,1065.80,53071.52,53230.82,52860.64,52993.25,370.18,131.05,...,1021.10,204.00,79.83,2024,4,1,2024,3,22,0
96,4,BANKEX,835.75,942.90,52924.59,53025.61,52362.46,52686.69,663.15,91.00,...,926.75,6.50,184.42,2024,3,22,2024,3,18,0
97,4,BANKEX,852.35,968.45,53700.20,54299.44,53312.32,53773.29,987.12,41.80,...,894.15,-7.55,-137.77,2024,3,18,2024,3,12,0
98,4,BANKEX,941.60,1117.75,53963.42,54032.40,53676.15,53803.52,356.25,142.15,...,1083.75,94.60,271.11,2024,3,11,2024,3,4,0
99,4,BANKEX,969.50,1157.25,52909.86,53022.83,52646.96,52789.33,375.87,125.85,...,1095.35,-8.15,-29.30,2024,3,4,2024,2,27,0

In [175]:
label_mapping_df = pd.DataFrame({
'name': df['index'].unique(),
'name_encoded': label_encoder.transform(df['index'].unique())
})

In [176]:
label_mapping_df

       name  name_encoded
0  FINNIFTY             1
1     NIFTY             2
2    SENSEX             3
3    BANKEX             0

In [177]:
df.drop(['index'],axis=1,inplace=True)

In [178]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   daysToExpiry       100 non-null    int64
 1   close              100 non-null    float64
 2   high               100 non-null    float64
 3   index_close        100 non-null    float64
 4   index_high         100 non-null    float64
 5   index_low          100 non-null    float64
 6   index_open         100 non-null    float64
 7   intradayMovement   100 non-null    float64
 8   intradayTotal      100 non-null    float64
 9   low                100 non-null    float64
 10  open               100 non-null    float64
 11  overnightExpected  100 non-null    float64
 12  overnightGap       100 non-null    float64
 13  expiry_year        100 non-null    int32
 14  expiry_month       100 non-null    int32
 15  expiry_day         100 non-null    int32
 16  date_year          100 non-null    int32
 17  date_month         100 non-null    int32
 18  date_day           100 non-null    int32
 19  index_encoded      100 non-null    int32
dtypes: float64(12), int32(7), int64(1)
memory usage: 13.0 KB

In [179]:
X=df.drop(['close','high','low','open'],axis=1)
Y1=df['close']
Y2=df['open']
Y3=df['high']
Y4=df['low']

In [180]:
from sklearn.linear_model import LinearRegression

In [181]:
lm_close=LinearRegression()

In [182]:
lm_close.fit(X,Y1)

LinearRegression()

In [183]:
lm_open=LinearRegression()

In [184]:
lm_open.fit(X,Y2)

LinearRegression()

In [185]:
lm_high=LinearRegression()

In [186]:
lm_high.fit(X,Y3)

LinearRegression()

In [187]:
lm_low=LinearRegression()

In [188]:
lm_low.fit(X,Y4)

LinearRegression()

In [189]:
lm_close.score(X,Y1)

0.9269565156235762

In [190]:
lm_open.score(X,Y2)

0.9292591695445473

In [191]:
lm_high.score(X,Y3)

0.9341010961723881

In [192]:
lm_low.score(X,Y4)

0.9138178139421066

In [195]:
df[df['index_encoded']==1]

,daysToExpiry,close,high,index_close,index_high,index_low,index_open,intradayMovement,intradayTotal,low,open,overnightExpected,overnightGap,expiry_year,expiry_month,expiry_day,date_year,date_month,date_day,index_encoded
0,0,1.05,115.05,21160.75,21213.05,21123.40,21142.45,89.65,100.35,1.05,101.40,0.00,0.00,2024,4,2,2024,4,2,1
1,0,5.60,124.10,20708.55,20761.95,20689.20,20731.85,72.75,118.50,5.60,124.10,0.00,0.00,2024,3,26,2024,3,26,1
2,0,1.35,93.30,20588.05,20632.75,20547.90,20579.45,84.85,91.95,1.10,93.30,0.00,0.00,2024,3,19,2024,3,19,1
3,0,2.30,171.00,20899.75,21054.35,20682.35,20847.15,372.00,98.40,2.00,100.70,0.00,0.00,2024,3,12,2024,3,12,1
4,0,4.40,117.95,20858.10,20951.55,20822.10,20842.10,129.45,112.35,3.75,116.75,0.00,0.00,2024,3,5,2024,3,5,1
5,1,121.55,185.85,21186.80,21229.10,21145.40,21164.10,83.70,59.50,113.45,181.05,20.15,44.35,2024,4,2,2024,4,1,1
6,1,134.40,196.10,20768.45,20838.35,20672.30,20738.10,166.05,58.15,134.20,192.55,10.30,36.60,2024,3,26,2024,3,22,1
7,1,140.75,209.60,20642.00,20699.20,20472.90,20579.80,226.30,68.85,138.55,209.60,47.45,62.55,2024,3,19,2024,3,18,1
8,1,123.85,184.95,20841.65,21010.10,20840.20,20973.05,169.90,58.10,123.85,181.95,23.15,-5.50,2024,3,12,2024,3,11,1
9,1,133.20,206.95,20916.40,20952.95,20813.45,20869.45,139.50,66.40,133.20,199.60,16.45,74.30,2024,3,5,2024,3,4,1
10,2,185.50,237.50,20996.25,21135.05,20872.10,20872.10,262.95,32.90,181.20,218.40,4.45,-167.85,2024,4,2,2024,3,28,1
11,2,201.35,254.95,20714.25,20818.30,20665.00,20714.55,153.30,41.80,196.70,243.15,8.80,-23.85,2024,3,26,2024,3,21,1
12,2,212.00,281.05,20618.50,20704.50,20536.45,20658.80,168.05,50.80,207.90,262.80,2.40,38.70,2024,3,19,2024,3,15,1
13,2,195.05,270.60,20989.30,21057.05,20955.75,21021.15,101.30,75.55,193.25,270.60,13.10,16.25,2024,3,12,2024,3,7,1
14,2,237.50,277.90,20821.00,20859.20,20540.15,20558.90,319.05,31.30,236.20,268.80,37.90,-48.45,2024,3,5,2024,3,1,1
15,3,227.15,275.85,20819.70,20852.80,20742.80,20763.70,110.00,48.70,220.95,275.85,8.75,-52.40,2024,4,2,2024,3,27,1
16,3,269.00,309.00,20562.85,20678.15,20373.65,20625.65,304.50,39.75,260.90,308.75,25.85,-151.70,2024,3,26,2024,3,20,1
17,3,259.10,364.25,20731.35,20861.95,20598.15,20656.40,263.80,88.90,256.60,348.00,-3.70,72.55,2024,3,19,2024,3,14,1
18,3,283.20,330.45,20994.55,21052.55,20825.70,20825.70,226.85,19.60,274.55,302.80,12.60,-26.60,2024,3,12,2024,3,6,1
19,3,275.60,391.00,20469.95,20489.40,20242.75,20307.30,246.65,115.40,271.55,391.00,6.80,-88.95,2024,3,5,2024,2,29,1
20,4,280.90,338.70,20708.55,20761.95,20689.20,20731.85,72.75,32.50,278.15,313.40,5.05,-55.15,2024,4,2,2024,3,26,1
21,4,327.65,376.00,20588.05,20632.75,20547.90,20579.45,84.85,42.25,315.35,369.90,18.90,-37.60,2024,3,26,2024,3,19,1
22,4,326.70,354.55,20734.55,20951.75,20705.45,20951.75,246.30,20.80,308.80,347.50,-21.30,78.15,2024,3,19,2024,3,13,1
23,4,316.30,398.80,20858.10,20951.55,20822.10,20842.10,129.45,77.00,315.85,393.30,13.50,32.40,2024,3,12,2024,3,5,1
24,4,403.40,416.50,20318.40,20625.75,20317.80,20576.00,307.95,-26.50,339.80,376.90,12.40,11.10,2024,3,5,2024,2,28,1

Here I am taking FINNIFTY record that expired on 2nd April 2024. I am assuming the same record is there when it expired on 9th April 2024 and predicting the straddle high,low,close and open for tomorrow, 6th April 2024

In [196]:
X_pred=[[4,20708.55,20761.95,20689.20,20731.85,72.75,32.50,5.05,-55.15,2024,4,9,2024,4,6,1]]

In [197]:
Y_pred_close=lm_close.predict(X_pred)
Y_pred_close

C:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([326.02404966])

In [198]:
Y_pred_open=lm_open.predict(X_pred)
Y_pred_open

C:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([358.52404966])

In [201]:
Y_pred_high=lm_high.predict(X_pred)
Y_pred_high

C:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([345.4229921])

In [202]:
Y_pred_low=lm_low.predict(X_pred)
Y_pred_low

C:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([293.25784354])